apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: massive-attack
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '600m'
    nginx.org/client-max-body-size: '600m'
spec:
  tls:
    - hosts:
        - sabiane-data.dev.insee.io
  rules:
    - host: sabiane-data.dev.insee.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: massive-attack
                port:
                  number: 8080
